add proxy support
Azure/azure-relay-aspnetserver pull request #27
Opened 2021-02-22 19:40 UTC by adrosa

adds Proxy to AzureRelayOptions and passes it on to the HybridConnectionListener

2021-02-22 23:15 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayListener.cs
> +                            relayListener.Proxy = Options.Proxy;
>Proxy [](start = 42, length = 5)

HybridConnectionListener uses the system webproxy if HybridConnectionListener.Proxy property is _never_ set. If the Proxy property is set to `null` then that means use no proxy, even if there's a Default WebProxy. Always assigning to null here would cause HybridConnectionListener to never pick up the system WebProxy.

Reference:
[https://github.com/Azure/azure-relay-dotnet/pull/108](https://github.com/Azure/azure-relay-dotnet/pull/108)

2021-02-22 23:25 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayListener.cs
> +                            relayListener.Proxy = Options.Proxy;
This is the way the underlying ClientWebSocket from .NET Core works. If one doesn't touch the ClientWebSocketOptions.Proxy property then any system configured proxy is used. If the user explicitly sets ClientWebSocketOptions.Proxy to null then any system configured proxy is not used.

https://github.com/dotnet/runtime/blob/dcef2897eb61012d6e8c2ccc44e72eb7c173e06b/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L114

2021-02-23 21:26 UTC, adrosa commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayListener.cs
> +                            relayListener.Proxy = Options.Proxy;
fixed

2021-02-23 21:28 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayOptions.cs
> +        public bool UseCustomProxy { get; set; }
Please remove the extra empty lines so there's only one (same thing a few lines below).

2021-02-23 21:29 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayListener.cs
> +                            if( Options.UseCustomProxy )
>  [](start = 31, length = 1)

Remove extra spaces between parentheses

2021-02-23 21:30 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayListener.cs
> +                                relayListener.Proxy = Options.Proxy;
Place brackets around the code inside the "if".

2021-02-23 21:30 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayListener.cs
> +                            // TODO: should i always set this?
>TODO: should i always set this? [](start = 31, length = 31)

Is this TODO still applicable? It looks like the TODO is now done.

2021-02-23 21:31 UTC, dlstucki commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayOptions.cs
> +        private IWebProxy proxy;
>private IWebProxy proxy; [](start = 8, length = 24)

fields go before constructors

2021-02-23 21:33 UTC, dlstucki requested changes
:clock1:

2021-02-23 21:39 UTC, adrosa commented on src/Microsoft.Azure.Relay.AspNetCore/AzureRelayOptions.cs
> +        private IWebProxy proxy;
i think this might be an exception. full property should be next to its backing.

2021-02-24 00:07 UTC, dlstucki approved these changes
:shipit:

2021-02-24 01:38 UTC, merged